name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore DotnetCiDemo/DotnetCiDemo.csproj

    - name: Build
      run: dotnet build DotnetCiDemo/DotnetCiDemo.csproj --no-restore

    - name: Test
      run: dotnet test DotnetCiDemo.Tests/DotnetCiDemo.Tests.csproj --no-build --verbosity normal
